"""
Integration tests for speech queue priority behaviour.

Two scenarios tested end-to-end through the real TextToSpeechRunner /
JobQueue / Voice stack (TTS provider and sox stubbed out):

1. Signoff / scheduled shutdown
   Voice.clear_queue() must empty any pre-existing pending jobs so the
   shutdown announcement becomes the first item in an otherwise empty queue,
   not the last item behind whatever the DJ was already preparing to say.

2. Extension announcement ordering
   ExtensionManager calls voice.prepare_to_say(text, save_for_last=True)
   from a background thread.  The announcement must land *after* every chunk
   already being generated by a concurrent speak() call.  Without the
   _active_generations counter this was a race: if the extension thread saw
   an empty queue it would proceed immediately and get sandwiched before the
   chunks that were about to be added.
"""
import threading
import time
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from tts.providers import BaseTTSProvider, TTSProviderType
from tts.tts_runner import TTSConfig, TextToSpeechRunner


# ---------------------------------------------------------------------------
# Shared stub / factory helpers
# ---------------------------------------------------------------------------

class _StubProvider(BaseTTSProvider):
    """Stub provider: creates an empty file without doing any real synthesis."""

    def __init__(self, generation_delay: float = 0.0):
        self._delay = generation_delay

    def load(self) -> None:
        pass

    def generate_speech_file(self, text: str, output_path: str, **kwargs) -> None:
        if self._delay:
            time.sleep(self._delay)
        Path(output_path).touch()

    def supports_voice_cloning(self) -> bool:
        return False

    def supported_languages(self):
        return []

    def is_available(self) -> bool:
        return True

    def metadata_info(self):
        return {}


def _make_runner(tmp_path, monkeypatch, generation_delay: float = 0.0) -> TextToSpeechRunner:
    """Return a TextToSpeechRunner backed by the stub provider.

    combine_audio_files is replaced with a no-op so sox is never invoked.
    """
    provider = _StubProvider(generation_delay=generation_delay)
    monkeypatch.setattr("tts.tts_runner.get_provider", lambda config: provider)

    config = TTSConfig(
        model=None,
        provider=TTSProviderType.COQUI,
        filepath=str(tmp_path / "tts_test"),
        auto_play=False,
        delete_interim_files=False,
        overwrite=True,
    )
    runner = TextToSpeechRunner(config)
    runner.combine_audio_files = MagicMock(return_value=None)
    return runner


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@pytest.mark.integration
class TestSignoffClearsQueue:
    """Voice.clear_queue() removes all pending jobs before signoff speech is added."""

    def test_pre_existing_jobs_removed_before_signoff(self, tmp_path, monkeypatch):
        """Items queued from an in-progress spot are purged by clear_queue()."""
        runner = _make_runner(tmp_path, monkeypatch)

        # Simulate speech that was already queued from spot preparation.
        runner.speech_queue.add("intro_chunk_1.wav")
        runner.speech_queue.add("intro_chunk_2.wav")
        runner.speech_queue.add("commentary.wav")
        assert len(runner.speech_queue.pending_jobs) == 3

        # sign_off() calls voice.clear_queue() which calls speech_queue.cancel().
        runner.speech_queue.cancel()

        assert runner.speech_queue.pending_jobs == []
        assert not runner.speech_queue.job_running

    def test_signoff_item_is_first_after_clear(self, tmp_path, monkeypatch):
        """After clearing, only the signoff speech occupies the queue."""
        runner = _make_runner(tmp_path, monkeypatch)

        runner.speech_queue.add("old_speech.wav")
        runner.speech_queue.add("more_old_speech.wav")

        runner.speech_queue.cancel()
        runner.speech_queue.add("signoff.wav")

        assert runner.speech_queue.pending_jobs == ["signoff.wav"]

    def test_clear_queue_is_idempotent_on_empty_queue(self, tmp_path, monkeypatch):
        """Calling clear_queue on an already-empty queue does not raise."""
        runner = _make_runner(tmp_path, monkeypatch)
        assert not runner.speech_queue.has_pending()
        runner.speech_queue.cancel()  # must not raise
        assert not runner.speech_queue.has_pending()


@pytest.mark.integration
class TestExtensionAnnouncementOrdering:
    """Extension announcement via save_for_last=True always follows generated chunks."""

    def test_extension_waits_for_active_generation(self, tmp_path, monkeypatch):
        """await_pending_speech_jobs(run_jobs=False) blocks while _active_generations > 0."""
        runner = _make_runner(tmp_path, monkeypatch)

        proceeded = threading.Event()
        generation_started = threading.Event()

        def simulate_generation():
            with runner._generation_condition:
                runner._active_generations += 1
            generation_started.set()
            time.sleep(0.1)
            with runner._generation_condition:
                runner._active_generations -= 1
                runner._generation_condition.notify_all()

        def simulate_extension():
            generation_started.wait()
            runner.await_pending_speech_jobs(run_jobs=False)
            proceeded.set()

        gen_t = threading.Thread(target=simulate_generation)
        ext_t = threading.Thread(target=simulate_extension)
        gen_t.start()
        ext_t.start()
        gen_t.join(timeout=5)
        ext_t.join(timeout=5)

        assert proceeded.is_set(), "Extension should have proceeded after generation finished"

    def test_extension_item_ordered_after_concurrent_chunks(self, tmp_path, monkeypatch):
        """Extension item lands after all chunks from a concurrently running speak().

        With auto_play=False, chunks sit in the queue until finish_speaking() drains
        them.  The extension thread (save_for_last=True) therefore waits for:
          1. _active_generations == 0   (generation lock — the new fix)
          2. has_pending() == False     (queue drained — pre-existing behaviour)

        The test simulates step 2 by calling speech_queue.cancel() from the main
        thread after speak_t finishes, mirroring what finish_speaking() does at
        runtime.  This unblocks the extension thread, which must then append its
        item *after* all three chunk entries already recorded by tracked_add.
        """
        runner = _make_runner(tmp_path, monkeypatch, generation_delay=0.04)

        added_order = []
        original_add = runner.speech_queue.add

        def tracked_add(filepath):
            added_order.append(Path(filepath).name)
            return original_add(filepath)

        runner.speech_queue.add = tracked_add

        generation_started = threading.Event()
        original_speak_callback = runner._speak

        def patched_speak(text, invocation):
            generation_started.set()  # signal after first chunk starts generating
            original_speak_callback(text, invocation)

        runner._speak = patched_speak

        multi_paragraph = "First sentence.\n\nSecond sentence.\n\nThird sentence."

        def do_extension():
            generation_started.wait()
            # Mirrors extension_manager: wait for active generation + queue drain.
            runner.await_pending_speech_jobs(run_jobs=False)
            # tracked_add records the entry; no separate append needed.
            runner.speech_queue.add("extension_announcement.wav")

        speak_t = threading.Thread(target=lambda: runner.speak(multi_paragraph))
        ext_t = threading.Thread(target=do_extension)

        speak_t.start()
        ext_t.start()
        speak_t.join(timeout=10)
        # Simulate finish_speaking() draining the queue so the extension thread
        # can proceed past the has_pending() wait.
        runner.speech_queue.cancel()
        ext_t.join(timeout=5)

        assert added_order, "Nothing was added to the queue"
        assert added_order[-1] == "extension_announcement.wav", (
            f"Extension did not land last: {added_order}"
        )
        # Every chunk must precede the extension item.
        ext_index = added_order.index("extension_announcement.wav")
        assert ext_index > 0, f"No chunks were generated before the extension: {added_order}"
        assert all(n != "extension_announcement.wav" for n in added_order[:ext_index]), (
            f"Unexpected duplicate before extension: {added_order}"
        )

    def test_extension_does_not_interleave_without_race(self, tmp_path, monkeypatch):
        """When speak() finishes before the extension fires, ordering is still correct."""
        runner = _make_runner(tmp_path, monkeypatch)

        # speak() completes fully first (no concurrent race).
        runner.speak("Only one sentence here.")

        added_order = list(runner.speech_queue.pending_jobs)

        # Extension fires after speak() returns — queue is non-empty, so it waits
        # for finish_speaking() to drain it.  Simulate the drain then check the
        # extension adds correctly to an empty queue.
        runner.speech_queue.cancel()  # drain (simulates finish_speaking completing)
        runner.speech_queue.add("extension_announcement.wav")

        assert runner.speech_queue.pending_jobs == ["extension_announcement.wav"]
